# Generated by Django 6.0.1 on 2026-01-14 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigle', models.CharField(max_length=20, unique=True)),
                ('denomination', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('secteursactivite', models.CharField(max_length=255)),
                ('villescouvertes', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('siteweb', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='entreprises/')),
            ],
        ),
    ]
